name: interpreter
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  colorize: ^3.0.0
  dartx: ^1.1.0
  path: ^1.8.2

dev_dependencies:
  dart_code_metrics: ^5.6.0
  lints: ^2.0.1
  test: ^1.21.1
